
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionLivresWS", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionLivresWS {


    /**
     * 
     * @return
     *     returns java.util.List<services.Livre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listerTousLesLivres", targetNamespace = "http://services/", className = "services.ListerTousLesLivres")
    @ResponseWrapper(localName = "listerTousLesLivresResponse", targetNamespace = "http://services/", className = "services.ListerTousLesLivresResponse")
    public List<Livre> listerTousLesLivres();

    /**
     * 
     * @param intitulé
     * @param auteurs
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterLivre", targetNamespace = "http://services/", className = "services.AjouterLivre")
    @ResponseWrapper(localName = "ajouterLivreResponse", targetNamespace = "http://services/", className = "services.AjouterLivreResponse")
    public void ajouterLivre(
        @WebParam(name = "intitul\u00e9", targetNamespace = "")
        String intitulé,
        @WebParam(name = "auteurs", targetNamespace = "")
        List<Auteur> auteurs);

}
